# .pre-commit-config.yaml
---
repos:
  - repo: https://github.com/psf/black.git
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python3
