[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "chisel4ml"
authors = [
    {name = "Jure Vreca", email = "jure.vreca@ijs.si"}
]
description = "A Chisel based hardware generation library for highly quantized neural networks."
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.7"
license = { file = "LICENSE" }
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent"
]
keywords = ["Chisel", "FPGA", "quantized neural networks"]
dynamic=["version"]
dependencies = [
    "QKeras==0.9.0",
    "grpcio>1.0.0",
    "protobuf<=3.20.0",
    "tf2-keras-surgeon",
    "pyparsing"
]

[tool.setuptools.dynamic]
version = {attr = "chisel4ml.__version__"}

[tool.setuptools_scm]
version_file = "chisel4ml/_version.py"


[project.optional-dependencies]
dev = [
    "tox<4",
	"tox-run-before",
	"flake8",
    "Flake8-pyproject",
	"pytest",
	"grpcio-tools",
    "mypy-protobuf",
	"setuptools>=61",
    "build",
    "librosa",
    "pre_commit",
    "tensorflow-datasets"
]

[project.urls]
Repository = "https://github.com/cs-jsi/chisel4ml"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ['.']
include = ['chisel4ml*']
exclude = ['chisel4ml.tests']
namespaces = false

[tool.pytest.ini_options]
addopts = ""
filterwarnings = ["ignore:::.*flatbuffers*", "ignore:::.*tensorflow*"]
testpaths = [
    "tests",
]

[tool.flake8]
extend-ignore = ["E203"]
max-line-length = 88
count= true
exclude=[
    ".git",
    "__pycache__",
    "docs",
    "build",
    "dist",
    "test_run_dir",
    "venv",
    "target",
    "project",
    "AUTHORS",
    "LICENSE",
    "MANIFEST.in",
    "pyproject.toml",
    "chisel4ml/_version.py",
    "ChangeLog",
    "Makefile",
    "*.hex",
    "*.ini",
    "*.md",
    "*.txt",
    "build.sbt",
    "chisel4ml/bin",
    "chisel4ml/lbir"
]

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.7.0
envlist = py37, py38, py39, py310, linters
isolated_build = true

[gh-actions]
python =
    3.7:  py37
    3.8:  py38
    3.9:  py39
    3.10: py310, linters

[testenv]
extras = dev
run_before = make protobuf
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest --basetemp={envtmpdir} tests/

[testenv:linters]
commands =
    flake8 chisel4ml tests
"""

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "chisel4ml/_version.py"
tag_prefix = ""
parentdir_prefix = "chisel4ml-"
