[build-system]
requires = ["pbr>=5.7.0", "setuptools>=42.0", "wheel"]
build-backend = "pbr.build"

[tool.pytest.ini_options]
addopts = "--cov=chisel4ml"
filterwarnings = ["ignore:::.*flatbuffers*", "ignore:::.*tensorflow*"]
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "chisel4ml"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
