"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import chisel4ml.lbir.lbir_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ModelRunReturn(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[chisel4ml.lbir.lbir_pb2.QTensor]: ...
    def __init__(self,
        *,
        values: typing.Optional[typing.Iterable[chisel4ml.lbir.lbir_pb2.QTensor]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values",b"values"]) -> None: ...
global___ModelRunReturn = ModelRunReturn

class ModelRunParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODELHANDLE_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    @property
    def modelHandle(self) -> global___ModelHandle: ...
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[chisel4ml.lbir.lbir_pb2.QTensor]: ...
    def __init__(self,
        *,
        modelHandle: typing.Optional[global___ModelHandle] = ...,
        inputs: typing.Optional[typing.Iterable[chisel4ml.lbir.lbir_pb2.QTensor]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["modelHandle",b"modelHandle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["inputs",b"inputs","modelHandle",b"modelHandle"]) -> None: ...
global___ModelRunParams = ModelRunParams

class ModelHandle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    DIRECTORY_FIELD_NUMBER: builtins.int
    REPLY_FIELD_NUMBER: builtins.int
    name: typing.Text
    directory: typing.Text
    @property
    def reply(self) -> global___ErrorMsg: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        directory: typing.Text = ...,
        reply: typing.Optional[global___ErrorMsg] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reply",b"reply"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["directory",b"directory","name",b"name","reply",b"reply"]) -> None: ...
global___ModelHandle = ModelHandle

class ErrorMsg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ErrorId:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ErrorIdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ErrorMsg._ErrorId.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUCCESS: ErrorMsg._ErrorId.ValueType  # 0
        FAIL: ErrorMsg._ErrorId.ValueType  # 1
    class ErrorId(_ErrorId, metaclass=_ErrorIdEnumTypeWrapper):
        pass

    SUCCESS: ErrorMsg.ErrorId.ValueType  # 0
    FAIL: ErrorMsg.ErrorId.ValueType  # 1

    ERR_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    err: global___ErrorMsg.ErrorId.ValueType
    msg: typing.Text
    def __init__(self,
        *,
        err: global___ErrorMsg.ErrorId.ValueType = ...,
        msg: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["err",b"err","msg",b"msg"]) -> None: ...
global___ErrorMsg = ErrorMsg
