addSbtPlugin("com.eed3si9n"     % "sbt-assembly" % "2.1.3")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix" % "0.11.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.eed3si9n"     % "sbt-unidoc"   % "0.4.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages"  % "0.6.2")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"     % "2.2.5")
addSbtPlugin("org.xerial.sbt"   % "sbt-pack"     % "0.9.3")
