# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LBIR.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LBIR.proto',
  package='chisel4ml',
  syntax='proto3',
  serialized_options=_b('\n\016chisel4ml.lbirB\013ModelProtosP\001'),
  serialized_pb=_b('\n\nLBIR.proto\x12\tchisel4ml\"7\n\x05Model\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x06layers\x18\x02 \x03(\x0b\x32\x10.chisel4ml.Layer\"\xe5\x01\n\x05Layer\x12.\n\nlayer_type\x18\x01 \x01(\x0e\x32\x1a.chisel4ml.Layer.LayerType\x12\x10\n\x08use_bias\x18\x02 \x01(\x08\x12#\n\x07weights\x18\x03 \x01(\x0b\x32\x12.chisel4ml.QTensor\x12\"\n\x06\x62iases\x18\x04 \x01(\x0b\x32\x12.chisel4ml.QTensor\x12-\n\x0finput_quantizer\x18\x05 \x01(\x0b\x32\x14.chisel4ml.Quantizer\"\"\n\tLayerType\x12\t\n\x05\x44\x45NSE\x10\x00\x12\n\n\x06\x43ONV2D\x10\x01\"B\n\x07QTensor\x12\'\n\tquantizer\x18\x01 \x01(\x0b\x32\x14.chisel4ml.Quantizer\x12\x0e\n\x06values\x18\x02 \x03(\x02\"\xb6\x01\n\tQuantizer\x12:\n\x0equantizer_type\x18\x01 \x01(\x0e\x32\".chisel4ml.Quantizer.QuantizerType\x12\x11\n\tbit_width\x18\x02 \x01(\r\x12\r\n\x05scale\x18\x03 \x01(\x02\x12\x0e\n\x06offset\x18\x04 \x01(\x02\";\n\rQuantizerType\x12\x19\n\x15SYMMETRIC_UNIFORM_PO2\x10\x00\x12\x0f\n\x0b\x42INARY_SIGN\x10\x01\x42\x1f\n\x0e\x63hisel4ml.lbirB\x0bModelProtosP\x01\x62\x06proto3')
)



_LAYER_LAYERTYPE = _descriptor.EnumDescriptor(
  name='LayerType',
  full_name='chisel4ml.Layer.LayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DENSE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONV2D', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=278,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_LAYER_LAYERTYPE)

_QUANTIZER_QUANTIZERTYPE = _descriptor.EnumDescriptor(
  name='QuantizerType',
  full_name='chisel4ml.Quantizer.QuantizerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYMMETRIC_UNIFORM_PO2', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BINARY_SIGN', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=506,
  serialized_end=565,
)
_sym_db.RegisterEnumDescriptor(_QUANTIZER_QUANTIZERTYPE)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='chisel4ml.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chisel4ml.Model.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layers', full_name='chisel4ml.Model.layers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=80,
)


_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='chisel4ml.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer_type', full_name='chisel4ml.Layer.layer_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_bias', full_name='chisel4ml.Layer.use_bias', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='chisel4ml.Layer.weights', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='biases', full_name='chisel4ml.Layer.biases', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_quantizer', full_name='chisel4ml.Layer.input_quantizer', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAYER_LAYERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=312,
)


_QTENSOR = _descriptor.Descriptor(
  name='QTensor',
  full_name='chisel4ml.QTensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantizer', full_name='chisel4ml.QTensor.quantizer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='chisel4ml.QTensor.values', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=380,
)


_QUANTIZER = _descriptor.Descriptor(
  name='Quantizer',
  full_name='chisel4ml.Quantizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantizer_type', full_name='chisel4ml.Quantizer.quantizer_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bit_width', full_name='chisel4ml.Quantizer.bit_width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale', full_name='chisel4ml.Quantizer.scale', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='chisel4ml.Quantizer.offset', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUANTIZER_QUANTIZERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=565,
)

_MODEL.fields_by_name['layers'].message_type = _LAYER
_LAYER.fields_by_name['layer_type'].enum_type = _LAYER_LAYERTYPE
_LAYER.fields_by_name['weights'].message_type = _QTENSOR
_LAYER.fields_by_name['biases'].message_type = _QTENSOR
_LAYER.fields_by_name['input_quantizer'].message_type = _QUANTIZER
_LAYER_LAYERTYPE.containing_type = _LAYER
_QTENSOR.fields_by_name['quantizer'].message_type = _QUANTIZER
_QUANTIZER.fields_by_name['quantizer_type'].enum_type = _QUANTIZER_QUANTIZERTYPE
_QUANTIZER_QUANTIZERTYPE.containing_type = _QUANTIZER
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER
DESCRIPTOR.message_types_by_name['QTensor'] = _QTENSOR
DESCRIPTOR.message_types_by_name['Quantizer'] = _QUANTIZER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'LBIR_pb2'
  # @@protoc_insertion_point(class_scope:chisel4ml.Model)
  ))
_sym_db.RegisterMessage(Model)

Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
  DESCRIPTOR = _LAYER,
  __module__ = 'LBIR_pb2'
  # @@protoc_insertion_point(class_scope:chisel4ml.Layer)
  ))
_sym_db.RegisterMessage(Layer)

QTensor = _reflection.GeneratedProtocolMessageType('QTensor', (_message.Message,), dict(
  DESCRIPTOR = _QTENSOR,
  __module__ = 'LBIR_pb2'
  # @@protoc_insertion_point(class_scope:chisel4ml.QTensor)
  ))
_sym_db.RegisterMessage(QTensor)

Quantizer = _reflection.GeneratedProtocolMessageType('Quantizer', (_message.Message,), dict(
  DESCRIPTOR = _QUANTIZER,
  __module__ = 'LBIR_pb2'
  # @@protoc_insertion_point(class_scope:chisel4ml.Quantizer)
  ))
_sym_db.RegisterMessage(Quantizer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
