// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package lbir

object LbirProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      lbir.Model,
      lbir.Layer,
      lbir.QTensor,
      lbir.Quantizer
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgpsYmlyLnByb3RvEgljaGlzZWw0bWwiXQoFTW9kZWwSHQoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lEjUKBmxheWVyc
  xgCIAMoCzIQLmNoaXNlbDRtbC5MYXllckIL4j8IEgZsYXllcnNSBmxheWVycyLaAwoFTGF5ZXISSQoKbGF5ZXJfdHlwZRgBIAEoD
  jIaLmNoaXNlbDRtbC5MYXllci5MYXllclR5cGVCDuI/CxIJbGF5ZXJUeXBlUglsYXllclR5cGUSJwoIdXNlX2JpYXMYAiABKAhCD
  OI/CRIHdXNlQmlhc1IHdXNlQmlhcxI6Cgd3ZWlnaHRzGAMgASgLMhIuY2hpc2VsNG1sLlFUZW5zb3JCDOI/CRIHd2VpZ2h0c1IHd
  2VpZ2h0cxI3CgZiaWFzZXMYBCABKAsyEi5jaGlzZWw0bWwuUVRlbnNvckIL4j8IEgZiaWFzZXNSBmJpYXNlcxJSCg9pbnB1dF9xd
  WFudGl6ZXIYBSABKAsyFC5jaGlzZWw0bWwuUXVhbnRpemVyQhPiPxASDmlucHV0UXVhbnRpemVyUg5pbnB1dFF1YW50aXplchIgC
  gV3aWR0aBgGIAEoDUIK4j8HEgV3aWR0aFIFd2lkdGgSIwoGaGVpZ2h0GAcgASgNQgviPwgSBmhlaWdodFIGaGVpZ2h0EikKCGNoY
  W5uZWxzGAggASgNQg3iPwoSCGNoYW5uZWxzUghjaGFubmVscyIiCglMYXllclR5cGUSCQoFREVOU0UQABIKCgZDT05WMkQQASJyC
  gdRVGVuc29yEkIKCXF1YW50aXplchgBIAEoCzIULmNoaXNlbDRtbC5RdWFudGl6ZXJCDuI/CxIJcXVhbnRpemVyUglxdWFudGl6Z
  XISIwoGdmFsdWVzGAIgAygCQgviPwgSBnZhbHVlc1IGdmFsdWVzIo4CCglRdWFudGl6ZXISQQoEdHlwZRgBIAEoDjIiLmNoaXNlb
  DRtbC5RdWFudGl6ZXIuUXVhbnRpemVyVHlwZUIJ4j8GEgR0eXBlUgR0eXBlEioKCWJpdF93aWR0aBgCIAEoDUIN4j8KEghiaXRXa
  WR0aFIIYml0V2lkdGgSIAoFc2NhbGUYAyABKAJCCuI/BxIFc2NhbGVSBXNjYWxlEiMKBm9mZnNldBgEIAEoAkIL4j8IEgZvZmZzZ
  XRSBm9mZnNldCJLCg1RdWFudGl6ZXJUeXBlEhkKFVNZTU1FVFJJQ19VTklGT1JNX1BPMhAAEg8KC0JJTkFSWV9TSUdOEAESDgoKQ
  klOQVJZX1BPMhACQhUKBGxiaXJCC01vZGVsUHJvdG9zUAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}