// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package lbir

object LbirProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      lbir.Model,
      lbir.Layer,
      lbir.QTensor,
      lbir.Quantizer
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgpsYmlyLnByb3RvEgljaGlzZWw0bWwiXQoFTW9kZWwSHQoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lEjUKBmxheWVyc
  xgCIAMoCzIQLmNoaXNlbDRtbC5MYXllckIL4j8IEgZsYXllcnNSBmxheWVycyLYAwoFTGF5ZXISSAoJbGF5ZXJUeXBlGAEgASgOM
  houY2hpc2VsNG1sLkxheWVyLkxheWVyVHlwZUIO4j8LEglsYXllclR5cGVSCWxheWVyVHlwZRInCgh1c2VfYmlhcxgCIAEoCEIM4
  j8JEgd1c2VCaWFzUgd1c2VCaWFzEjoKB3dlaWdodHMYAyABKAsyEi5jaGlzZWw0bWwuUVRlbnNvckIM4j8JEgd3ZWlnaHRzUgd3Z
  WlnaHRzEjcKBmJpYXNlcxgEIAEoCzISLmNoaXNlbDRtbC5RVGVuc29yQgviPwgSBmJpYXNlc1IGYmlhc2VzElEKDmlucHV0UXVhb
  nRpemVyGAUgASgLMhQuY2hpc2VsNG1sLlF1YW50aXplckIT4j8QEg5pbnB1dFF1YW50aXplclIOaW5wdXRRdWFudGl6ZXISIAoFd
  2lkdGgYBiABKA1CCuI/BxIFd2lkdGhSBXdpZHRoEiMKBmhlaWdodBgHIAEoDUIL4j8IEgZoZWlnaHRSBmhlaWdodBIpCghjaGFub
  mVscxgIIAEoDUIN4j8KEghjaGFubmVsc1IIY2hhbm5lbHMiIgoJTGF5ZXJUeXBlEgkKBURFTlNFEAASCgoGQ09OVjJEEAEicgoHU
  VRlbnNvchJCCglxdWFudGl6ZXIYASABKAsyFC5jaGlzZWw0bWwuUXVhbnRpemVyQg7iPwsSCXF1YW50aXplclIJcXVhbnRpemVyE
  iMKBnZhbHVlcxgCIAMoAkIL4j8IEgZ2YWx1ZXNSBnZhbHVlcyKQAgoJUXVhbnRpemVyEkQKBXF0eXBlGAEgASgOMiIuY2hpc2VsN
  G1sLlF1YW50aXplci5RdWFudGl6ZXJUeXBlQgriPwcSBXF0eXBlUgVxdHlwZRIpCghiaXRXaWR0aBgCIAEoDUIN4j8KEghiaXRXa
  WR0aFIIYml0V2lkdGgSIAoFc2NhbGUYAyABKAJCCuI/BxIFc2NhbGVSBXNjYWxlEiMKBm9mZnNldBgEIAEoAkIL4j8IEgZvZmZzZ
  XRSBm9mZnNldCJLCg1RdWFudGl6ZXJUeXBlEhkKFVNZTU1FVFJJQ19VTklGT1JNX1BPMhAAEg8KC0JJTkFSWV9TSUdOEAESDgoKQ
  klOQVJZX1BPMhACQhUKBGxiaXJCC01vZGVsUHJvdG9zUAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}