
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: 'sbt'

    - name: Install verilator
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: verilator
        version: 1.0

    - name: Build scala
      run: |
          sbt --no-colors protocGenerate
          sbt --no-colors assembly

    - name: Make protobuf
      run: make protobuf

    - name: Spin up a chisel4ml server
      run: java -jar chisel4ml/bin/chisel4ml.jar &> chisel4ml_sever.log &

    - name: Test with tox
      run: python -m tox -vv

    - name: Cat logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: chisel4ml_server.log
        path: chisel4ml_server.log
